### ISSUE TITLE
Probably an incorrect test case testAuthorityIsPrefixedByDoubleSlashIfPresent in UriTest.php

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-diactoros#1]
Two tests are looking identical despite description. Probably withHost in second case should be replaced by something else.

```
    public function testUriDoesNotAppendColonToHostIfPortIsEmpty()
    {
        $uri = (new Uri())->withHost('google.com');
        $this->assertSame('//google.com', (string) $uri);
    }
    public function testAuthorityIsPrefixedByDoubleSlashIfPresent()
    {
        $uri = (new Uri())->withHost('example.com');
        $this->assertSame('//example.com', (string) $uri);
    }
```

---

Originally posted by @Keksov at https://github.com/zendframework/zend-diactoros/issues/381

**Comment by Xerkus** [comment]
Tests body looks similar but they are not the same.

If either of expectations breaks both tests will fail but test names describe the expectation which in turn allows to properly interpret failure and to refactor test with same expectation but different code if needed.
