### ISSUE TITLE
Invalid size provided for UploadedFile; must be an int.

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-diactoros#10]
Hi guys, I'm working on an iOS project and I'm required to send documents, such as pdfs, to my laravel server. The issue is, every time I try to send a post request for a PDF, I get this error message: `Invalid size provided for UploadedFile; must be an int`. I'm at my wit's end trying to solve this issue. Any ideas?

---

Originally posted by @ImmanuelKannan at https://github.com/zendframework/zend-diactoros/issues/316

**Comment by weierophinney** [comment]
That exception is thrown here https://github.com/zendframework/zend-diactoros/blob/167607290e79c396fd947cedeadccce0173c0e47/src/UploadedFile.php#L113-L115

That is all I can derive from the description, you need to be more specific. Stack traces, anything?

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-diactoros/issues/316#issuecomment-405119085

**Comment by weierophinney** [comment]
If laravel uses `ServerRequestFactory` to create request from php globals, try to do `var_dump($_FILES); exit;` with failing request and post result here

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-diactoros/issues/316#issuecomment-405119510

**Comment by weierophinney** [comment]
Increase upload_max_filesize in php.ini

;Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 16M

Then
Restart Apache

---

Originally posted by @mrnaghibi at https://github.com/zendframework/zend-diactoros/issues/316#issuecomment-407001360

**Comment by halfpastfouram** [comment]
While this error itself will no longer occur, almost the same problem still happens in 2.3.0. When receiving the uploaded files from a request:

```
Argument 2 passed to Laminas\Diactoros\UploadedFile::__construct() must be of the type integer, string given, called in src/functions/create_uploaded_file.php on line 38
```

This can be easily fixed in the code by casting both the file size and the error code as an integer. I'll be making an PR for this.
