### ISSUE TITLE
Update to PSR-7 1.1/2.0

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-diactoros#132]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes

#### Summary

PSR-7 has just released tags for 1.1 and 2.0. 1.1 adds parameter type hints, and 2.0 adds return type hints.

For our purposes, we'll need to do a new minor and a new major:

- The new minor will bump to `^1.1` of the spec, and basically require no changes on our part. Since you can widen parameter types, we can omit them from in this release and still conform to the spec. We already provide return type hints in our implementation; again, these conform to the LSP, as you can have more specific RTH.
- The new major will bump to `^1.1 || ^2.0`, and add parameter type hints.

I've actually already done the work for these releases when I worked on the PSR-7 errata that introduced the new tags, and will get patches submitted this week.

The bigger issue will be updating all code depending on Diactoros and/or PSR-7.

**Comment by boesing** [comment]
FYI
https://github.com/php-http/psr7-integration-tests/pull/65

**Comment by weierophinney** [comment]
Resolved with #136
