### ISSUE TITLE
PhpInputStream's getSize function is Wrong!

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-diactoros#2]
reference: https://www.php.net/manual/en/wrappers.php.php
php://input is not support fstat

Supports stat() | php://memory and php://temp only.
-- | --

- [ ] I was not able to find an [open](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/c/questions/expressive).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
```

### Actual results

---

Originally posted by @zhushengwen at https://github.com/zendframework/zend-diactoros/issues/380

**Comment by weierophinney** [comment]
@zhushengwen 

[`fstat`](https://www.php.net/fstat) and [`stat`](https://www.php.net/stat) are two different PHP functions.

Can you provide failing test case, please?

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-diactoros/issues/380#issuecomment-559704878

**Comment by weierophinney** [comment]
![image](https://user-images.githubusercontent.com/5299147/69861972-6a0fab80-12d4-11ea-8561-e2aacf0c61fb.png)


---

Originally posted by @zhushengwen at https://github.com/zendframework/zend-diactoros/issues/380#issuecomment-559738685

**Comment by weierophinney** [comment]
@zhushengwen 
Please create a pull request with an unit test which illustrates the problem.
It's very hard to reproduce the problem per screenshot. 😉 

Thanks in advance!

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-diactoros/issues/380#issuecomment-559756513

**Comment by Xerkus** [comment]
`fstat()` can not be used on input stream. Stream needs to be fully read into internal cache property before the size could be determined but read should not happen on `getSize()` invocation.

Because size can not be determined for php input stream `getSize()` returns `null` and that is a correct behavior.

However, investigating this issue I discovered another problem that I will report as a separate issue.

**Comment by boesing** [comment]
I recently had a look into guzzle and they do in fact pass the stream over to a `temp` stream:
https://github.com/guzzle/psr7/blob/fe18df3deb34d1e0eab8a63ef4fe2aeb2a8e8c94/src/Utils.php#L305-L310

Not sure if we should handle this as well.

**Comment by Xerkus** [comment]
We use property to store cached content. It should really be temp stream, but I do not think we should eagerly read it for metadata and such.
