### ISSUE TITLE
Zend Framework Bridge is a required dependency

### ISSUE THREAD

**Issue by hexus** [laminas/laminas-diactoros#35]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.x

#### Summary

The Diactoros package currently forces installation of the Zend Framework bridge package, `laminas/laminas-zendframework-bridge`. For projects that can switch over easily, this is a completely unnecessary dependency.

Unless I'm missing something crucial here, I would instead recommend placing this dependency in the [`suggest` configuration of the `composer.json`](https://getcomposer.org/doc/04-schema.md#suggest) for this library.

#### Current behavior

Installing `laminas/laminas-diactoros` via Composer forces the installation of `laminas/laminas-zendframework-bridge`.

#### How to reproduce

```bash
composer require laminas/laminas-diactoros
```

Both the Diactoros library and the Zend Framework bridge are installed by Composer.

#### Expected behavior

Only the Diactoros library is installed by Composer.

**Comment by Xerkus** [comment]
It is required because laminas packages *replace* zend framework packages. To be a replacement laminas package should not break the code expecting zend framework package. That makes bridge a hard dependency. It will be dropped in next major release.

**Comment by hexus** [comment]
Right, next major version makes more sense. Thank you.
