### ISSUE TITLE
getQueryParams not returning proper data type

### ISSUE THREAD

**Issue by HagenMorano** [laminas/laminas-diactoros#39]
### Bug Report

zend-expressive v2.0.2

#### Summary

Do not know if this is a known issue or if this has already been fixed. The issue exists in zend-expressive v2.0.2. When accessing url query parameters via `$request->getQueryParams()`, integer values will be cast to string (e.g. `2` => `"2"`). I discovered this on parsing a query string encoded with `http_build_query` on an array.

Same thing happens when applying `parse_str($_SERVER['QUERY_STRING'])`.

#### Current behavior

`$request->getQueryParams()` casts integers to strings

#### How to reproduce

```
$aggregates = [
            'aggregates' => [
                'number' => 1
            ]
        ];
```

* `$client->request('GET', $myServiceUrl . '?' . http_build_query($aggregates))`
* Sends sth. like `[myServiceUrl]?aggregates%5Bnumber%5D=1` to your service
* `$params = $request->getQueryParams();`
* `var_dump($params['aggregates']) // number: "1"`

#### Expected behavior

`1` stays `1` :sunglasses: 

FYI @heiglandreas

**Comment by weierophinney** [comment]
Let's start with:

> Same thing happens when applying `parse_str($_SERVER['QUERY_STRING'])`.

and:

> - `$client->request('GET', $myServiceUrl . '?' . http_build_query($aggregates))

We'll start with a statement: query string arguments are presented as a string; hence the verbiage "query string". This is defined by the IETF specifications.

Now, when it comes to PHP, `http_build_query()` _creates a string representation_ of the arguments passed to it. `parse_str()` parses the string pass to it, has zero idea what the **types** of the arguments are, and, as such, it resolves all of the values as strings.

This is true of the behavior of `$_GET` as well. If you were to build a script with the following:

```php
<?php
http_response_code(200);
header('Content-Type: text/plain');

echo var_export($_GET, true), "\n";
```

and then pass it a URI with the query string "?aggregates%5Bnumber%5D=1", you'd get:

```text
array (
  'aggregates' =>
  array (
    'number' => '1',
  ),
)
```

Essentially, this is something we cannot change.

It's up to the _developer of the application_ to decide what the intended types are in this scenario, validate them, and, if necessary, cast them.
