### ISSUE TITLE
PSR-7 Integration Tests Failing

### ISSUE THREAD

**Issue by l0gicgate** [laminas/laminas-diactoros#74]
### Bug Report

The library is currently failing a `UriIntegrationTest`
https://github.com/php-http/psr7-integration-tests

|    Q        |   A
|------------ | ------
| Version(s)  | 2.8

#### Summary

<img alt="screenshot" src="https://camo.githubusercontent.com/9a744ca97a5087617a0794a298ffb0da29572797fd69e51d5a4470d01cf10fe4/68747470733a2f2f7075752e73682f49647579452f633535323835386335372e706e67" />

#### Current behavior

Fails the tests

#### How to reproduce

Run PSR-7 Integration Tests against this library

#### Expected behavior

Pass the tests

**Comment by boesing** [comment]
Related: https://github.com/php-http/psr7-integration-tests/pull/49
/cc @weierophinney

**Comment by weierophinney** [comment]
See #128 for a fix.
